# Generated by Django 3.0.1 on 2020-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_servicesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdata',
            name='cno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicesdata',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
